version: "3.2"
services:
  atlassian-db:
    image: postgres:12-alpine
    container_name: atlassian-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - type: bind
        source: ./postgres
        target: /var/lib/postgresql/data
    networks:
      network:
        aliases:
          - atlassian-db

networks:
  network:
    driver: bridge