version: "3.2"
services:
  confluence:
    image: atlassian/confluence:7-jdk11
    container_name: atlassian-confluence
    ports:
      - 8090:8090
    environment:
      #- JAVA_OPTS=-javaagent:/opt/atlassian/atlassian-agent.jar
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Database
      - ALT_JDBC_URL=jdbc:postgresql://atlassian-db:5432/confluence
      - ALT_JDBC_USER=confluence
      - ALT_JDBC_PASSWORD=confluence
      - ALT_JDBC_DRIVER=org.postgresql.Driver
    volumes:
      - type: bind
        source: ../atlassian-agent/atlassian-agent.jar
        target: /opt/atlassian/atlassian-agent.jar
    volumes:
      - type: bind
        source: ../application-data/confluence
        target: /var/atlassian/application-data/confluence
    networks:
      atlassian_network:
        aliases:
          - atlassian-confluence

networks:
  atlassian_network:
    external: true
