version: "3.2"
services:
  bitbucket:
    image: atlassian/bitbucket:7-jdk8 #jdk11 did not compatible with atlassian-agent
    container_name: atlassian-bitbucket
    ports:
      - 7990:7990
      - 7999:7999
    environment:
      - JAVA_OPTS=-javaagent:/opt/atlassian/atlassian-agent.jar
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Database
      - JDBC_URL=jdbc:postgresql://atlassian-db:5432/bitbucket
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=bitbucket
        JDBC_DRIVER=org.postgresql.Driver
    volumes:
      - type: bind
        source: ../application-data/bitbucket
        target: /var/atlassian/application-data/bitbucket/shared
    volumes:
      - type: bind
        source: ../atlassian-agent/atlassian-agent.jar
        target: /opt/atlassian/atlassian-agent.jar
    networks:
      atlassian_network:
        aliases:
          - atlassian-bitbucket

networks:
  atlassian_network:
    external: true
