version: "3.2"
services:
  jira:
    image: atlassian/jira-software:8-jdk11
    container_name: atlassian-jira
    ports:
      - 8080:8080
    environment:
      #- JAVA_OPTS=-javaagent:/opt/atlassian/atlassian-agent.jar
      # Memory / Heap Size
      - JVM_MINIMUM_MEMORY=512M
      - JVM_MAXIMUM_MEMORY=2048M
      # Database
      - ALT_JDBC_URL=jdbc:postgresql://atlassian-db:5432/jira
      - ALT_JDBC_USER=jira
      - ALT_JDBC_PASSWORD=jira
      - ALT_JDBC_DRIVER=org.postgresql.Driver
    volumes:
      - type: bind
        source: ../atlassian-agent/atlassian-agent.jar
        target: /opt/atlassian/atlassian-agent.jar
    volumes:
      - type: bind
        source: ../application-data/jira
        target: /var/atlassian/application-data/jira
    networks:
      atlassian_network:
        aliases:
          - atlassian-jira

networks:
  atlassian_network:
    external: true
